"""
Merge Request Creator Service
==============================
Handles pushing doc changes and creating a GitLab merge request
via the API as the final pipeline step.
"""

import logging

from services.gitlab_client import create_merge_request
from services.git_ops import commit_and_push

logger = logging.getLogger(__name__)


def create_docs_mr(
    repo,
    project_id: int,
    branch_name: str,
    target_branch: str,
    mr_iid: int,
    mr_title: str,
    mr_author: str,
    changed_files: list[str],
) -> dict | None:
    """
    Commit doc changes, push the feature branch, and create a GitLab MR.

    Returns the MR data dict (with web_url) on success, None on failure.
    """
    logger.info("🚀 Creating documentation merge request...")

    # 1. Build list of changed sections for commit message
    sections = set()
    for f in changed_files:
        parts = f.split("/")
        if len(parts) >= 2:
            sections.add(parts[1])  # docs/<section>/...
    sections_list = sorted(sections)

    # 2. Commit and push
    pushed = commit_and_push(repo, branch_name, mr_iid, sections_list)
    if not pushed:
        logger.info("📭 No changes to push — skipping MR creation.")
        return None

    # 3. Build MR description
    files_list = "\n".join(f"- `{f}`" for f in changed_files)
    description = f"""## 📝 Automated Documentation Update

This merge request was automatically generated by the Documentation Automation Pipeline.

### Trigger
- **Source MR:** !{mr_iid} — "{mr_title}"
- **Author:** {mr_author}

### Documentation Changes
{files_list}

### Updated Sections
{', '.join(f'`{s}`' for s in sections_list)}

---

> ⚙️ *This MR was created automatically. Please review the documentation changes before merging.*
"""

    # 4. Create MR via GitLab API
    mr_doc_title = f"docs: auto-update documentation for MR !{mr_iid}"
    mr_data = create_merge_request(
        project_id=project_id,
        source_branch=branch_name,
        target_branch=target_branch,
        title=mr_doc_title,
        description=description,
    )

    if mr_data:
        logger.info(
            "✅ Documentation MR created: %s",
            mr_data.get("web_url", "unknown"),
        )
    else:
        logger.error("❌ Failed to create documentation MR.")

    return mr_data
